### ISSUE TITLE
adb server didn't ACK

### ISSUE THREAD

**Issue by seojun0924** [nohajc/termux-adb#10]
Hello. I was wondering for non-root adb, and I think this one could only work with my phone.
It literally showed dialogue to allow Termux:API accessing SAMSUNG_Android.
But, after that, the messaged showed "adb server didn't ACK" message.
I used to have official termux adb builds, but it seems it is solved at latest release.

Please update this tool to latest version.

**Comment by nohajc** [comment]
Hi, I was planning to do the upgrade when I have more time.
I also heard there is a workaround for Samsung devices (could be related to your problem):
https://github.com/nohajc/termux-adb/issues/6

**Comment by seojun0924** [comment]
Thanks, it works. Maybe the adb hates from non-root user, but anyways. I will add it to .bashrc
