### ISSUE TITLE
 adb: No access to USB device requested

### ISSUE THREAD

**Issue by Qiihz** [nohajc/termux-adb#11]
![Screenshot_20230311173517](https://user-images.githubusercontent.com/33080214/224476808-4d7aca88-db4f-4c6b-98f9-cd5c1f051b50.jpg)

![Screenshot_20230311172146](https://user-images.githubusercontent.com/33080214/224476633-37267534-3ad1-4e83-b53e-b4864f72a87b.jpg)

Only when running `termux-fastboot devices`:
![Screenshot_20230311170954](https://user-images.githubusercontent.com/33080214/224476747-ddb3104e-7882-43cc-a629-ada19cdf7a5b.jpg)

**Comment by nohajc** [comment]
Can you try running `termux-adb kill-server` reconnecting the USB cable and running `termux-adb devices` again?

**Comment by Qiihz** [comment]
ok
