### ISSUE TITLE
Can't connect daemon

### ISSUE THREAD

**Issue by mcagabe19** [nohajc/termux-adb#14]
**Describe the bug**
termux-adb can't connect to deamon

**To Reproduce**
termux-adb devices

**Screenshots**
![Screenshot_20230625_163316_Termux](https://github.com/nohajc/termux-adb/assets/82843871/8396dcf6-a3bd-48b4-8269-c392a514418d)

**Smartphone:**
 - Device: Samsung A51
 - Android version: 13 aarch64

**Attach contents of the following files**
[adb.10320.log](https://github.com/nohajc/termux-adb/files/11859830/adb.10320.log)

**Comment by nohajc** [comment]
Is it possible there is another adb server already running? I would try both `adb kill-server` and `termux-adb kill-server`.

**Comment by nohajc** [comment]
Also, you might need the workaround mentioned in #6 .
