### ISSUE TITLE
Sir, can you write one for me 🙃; [like this](https://github.com/nohajc/vendor-adb-patched/blob/840f0b1e77f3aa5619cb3246cb269ebd3b21fe57/libtermuxadb/src/lib.rs) for  [my app](https://play.google.com/store/apps/details?id=com.rv882.adbify) but without ```termux-usb```

### ISSUE THREAD

**Issue by RohitVerma882** [nohajc/termux-adb#15]
Sir, can you write one for me 🙃; [like this](https://github.com/nohajc/vendor-adb-patched/blob/840f0b1e77f3aa5619cb3246cb269ebd3b21fe57/libtermuxadb/src/lib.rs) for  [my app](https://play.google.com/store/apps/details?id=com.rv882.adbify) but without ```termux-usb```

_Originally posted by @RohitVerma882 in https://github.com/nohajc/termux-adb/issues/1#issuecomment-1608764282_

**Comment by nohajc** [comment]
Hi. Sorry, I'm not planning to extend my tool beyond the termux ecosystem nor contribute to any other projects implementing similar functionality right now.

That being said, if you find out what termux-usb does internally (it just calls some Android SDK functions), it should be perfectly possible to use it in your app. Obviously you don't need the shell script wrapper.
