### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by Lolmc0587** [nohajc/termux-adb#17]
![Screenshot_20230829_133711_Termux](https://github.com/nohajc/termux-adb/assets/59377673/58ec99c8-9437-48e3-9f4f-deb849295eb4)

**Comment by nohajc** [comment]
This looks like the repository public key wasn't imported properly. Can you try deleting `$PREFIX/etc/apt/sources.list.d/termux-adb.list` and running `install.sh` again?

**Comment by Lolmc0587** [comment]
Thanks. It works

**Comment by Chit235** [comment]
![Screenshot_2024-04-10-13-17-12-672_com termux](https://github.com/nohajc/termux-adb/assets/166590518/ebba1186-9ceb-4f0a-a9f5-3a8c45a99085)
is not working how to fix

**Comment by nohajc** [comment]
What did you do exactly? Installing for the first time or trying to upgrade? I'm confused by the `rohitverma882.github.io` URL in the output.

I'm guessing you installed from a forked repo which is no longer available or something like that.

Try to start over (i.e. delete the repository from sources and run the installation script).
https://github.com/nohajc/termux-adb/issues/17#issuecomment-1697261287

**Comment by Chit235** [comment]
![Screenshot_2024-04-10-15-37-37-923_com termux](https://github.com/nohajc/termux-adb/assets/166590518/0f579bdb-5316-40e1-b9a7-41c33b7738f4)
![Screenshot_2024-04-10-15-37-50-652_com termux](https://github.com/nohajc/termux-adb/assets/166590518/96ab257e-0e2b-4e72-8f04-3f2ba54cf3ce)
![Screenshot_2024-04-10-15-49-12-854_com termux](https://github.com/nohajc/termux-adb/assets/166590518/0ed91fee-8bee-40e4-aacc-6eea67775819)
Why? ?

**Comment by nohajc** [comment]
I can try to replicate but it looks like you're having internet connection issues.
