### ISSUE TITLE
termux-adb broken by recent updates

### ISSUE THREAD

**Issue by Joomsy** [nohajc/termux-adb#19]
**Describe the bug**
Not exactly sure what updated to cause this, or rather, I assume something did, because this started happening after installing package updates. An error about creating an executable link is generated when attempting to run `termux-adb`.

```
> $ termux-adb
CANNOT LINK EXECUTABLE "termux-adb": cannot locate symbol "_ZN6google8protobuf11MessageLite15ParseFromStringEN4absl12lts_2023012511string_viewE" referenced by "/data/data/com.termux/files/usr/bin/termux-adb"...
```

**To Reproduce**
Just attempt to run `termux-adb`.

**Expected behavior**
`termux-adb` should execute, but doesn't.

**Smartphone (please complete the following information):**
 - Device: Pixel Fold
 - Android version: Android 13 (September patch)

**Attach output of the following commands**
- `RUST_LOG=debug ./termux-adb` (run with debug logs enabled)

```
> $ RUST_LOG=debug termux-adb
CANNOT LINK EXECUTABLE "termux-adb": cannot locate symbol "_ZN6google8protobuf11MessageLite15ParseFromStringEN4absl12lts_2023012511string_viewE" referenced by "/data/data/com.termux/files/usr/bin/termux-adb"...
```

- `pkg show android-tools` (show package info)

```
> $ pkg show android-tools
Package: android-tools
Version: 34.0.4-2
Maintainer: @termux
Installed-Size: 11.5 MB
Depends: abseil-cpp, brotli, libc++, liblz4, libprotobuf, libusb, pcre2, zlib, zstd
Homepage: https://developer.android.com/
Download-Size: 1744 kB
APT-Sources: https://plug-mirror.rcac.purdue.edu/termux/termux-main stable/main aarch64 Packages
Description: Android platform tools
```

- `adb version` (show adb version)

```
> $ adb version
Android Debug Bridge version 1.0.41
Version 34.0.4-android-tools
Installed as /data/data/com.termux/files/usr/bin/adb
Running on Linux 5.10.157-android13-4-00003-g776d0a76f6aa-ab10208116 (aarch64)
```

**Attach contents of the following files (after running with debug logs enabled)**
- `/data/data/com.termux/files/usr/tmp/adb.10233.log`

`No log generated`

- `/data/data/com.termux/files/usr/tmp/termux-adb.10233.log`

`No log generated`

**Additional context**
Attempting to run with logging enabled just produces the same result.

**Comment by nohajc** [comment]
Thank you for reporting this. It's the protobuf dependency.

I need to produce and release a new build. Ideally, I would do periodic automated builds to catch this kind of breakage early but I haven't had the time to set it up yet...

**Comment by Joomsy** [comment]
> Thank you for reporting this. It's the protobuf dependency.
> 
> I need to produce and release a new build. Ideally, I would do periodic automated builds to catch this kind of breakage early but I haven't had the time to set it up yet...

Ah, good to know! And thank you for the quick response. That's also completely understandable. No rush from me for a fix. I can fall back on a PC for the time being, but glad I could bring this to your attention.

**Comment by TeaOwO** [comment]
This also happens to me!

**Comment by nohajc** [comment]
There are some complications but I started working on a fix.

**Comment by nohajc** [comment]
Try to upgrade now. It should work again.

**Comment by nohajc** [comment]
I also took the opportunity to update to the latest version of android-tools instead of just recompiling the old one.

**Comment by Joomsy** [comment]
Everything looks good from my end. I didn't test much, but I was able to pair and connect to local wireless debugging, and run a shell command.
