### ISSUE TITLE
adb command giving error after new update 

### ISSUE THREAD

**Issue by DelightReza** [nohajc/termux-adb#23]
$termux-adb devices                                 * daemon not running; starting now at tcp:5037
error: expected absolute path: "-L"
ADB server didn't ACK
Full server startup log: /data/data/com.termux/files/usr/tmp/adb.10256.log
Server had pid: 7105
* failed to start daemon
linker64: failed to check server version: cannot connect to daemon

**Comment by nohajc** [comment]
Do you mean Termux update?

**Comment by DelightReza** [comment]
~ $ pkg show termux-adb
Package: termux-adb
Version: 0.2.2-1
Maintainer: nohajc
Installed-Size: 6296 kB
Depends: brotli, libc++, liblz4, libprotobuf-tadb-core, libusb, termux-api, zlib, zstd
Homepage: https://github.com/nohajc/termux-adb
Download-Size: 1585 kB
APT-Manual-Installed: yes
APT-Sources: https://nohajc.github.io termux/extras aarch64 Packages
Description: Run adb and fastboot in Termux without root permissions

Notice: There is 1 additional record. Please use the '-a' switch to see it
~ $ pkg show libprotobuf
Package: libprotobuf
Version: 25.1-2
Maintainer: @termux
Installed-Size: 6967 kB
Depends: abseil-cpp, libc++, zlib
Breaks: libprotobuf-dev, protobuf-static (<< 25.1)
Replaces: libprotobuf-dev
Homepage: https://github.com/protocolbuffers/protobuf
Download-Size: 1088 kB
APT-Manual-Installed: no
APT-Sources: https://termux.net stable/main aarch64 Packages
Description: Protocol buffers C++ library

~ $ pkg show libprotobuf-tadb-core
Package: libprotobuf-tadb-core
Version: 2:25.1
Maintainer: @termux
Installed-Size: 2757 kB
Depends: abseil-cpp, libc++, zlib
Homepage: https://github.com/protocolbuffers/protobuf
Download-Size: 666 kB
APT-Manual-Installed: no
APT-Sources: https://nohajc.github.io termux/extras aarch64 Packages
Description: Renamed libprotobuf library for termux-adb

**Comment by nohajc** [comment]
Interesting, I'm on version 0.118.1 and cannot reproduce the issue.

**Comment by DelightReza** [comment]
> Interesting, I'm on version 0.118.1 and cannot reproduce the issue.

Pay store version or Fdroid

**Comment by nohajc** [comment]
F-Droid. The Play Store version isn't supported.

**Comment by DelightReza** [comment]
> F-Droid. The Play Store version isn't supported.

I used play store version, so that's why
