### ISSUE TITLE
How do you actually use this to run ADB commands?

### ISSUE THREAD

**Issue by TheOnlineUser** [nohajc/termux-adb#24]
I followed the instructions on the main page, but I'm not able to actually use ADB.

Running "termux-adb" yields an error, so that doesn't seem like it's a real command.

Running "adb" prompts me to do pkg install android-tools. I did that, but then running adb devices doesn't detect my device (even with wireless debugging enabled).

This seems like it should be a pretty straightforward thing to do, unless this isn't meant to run ADB commands on your own device (in which case I'm puzzled about its use case). How can you actually get your own device to show up when running ADB?

**Comment by nohajc** [comment]
You are supposed to use the `termux-adb` command as an `adb` replacement.

Can you share the error message here? I need more information.

**Comment by nohajc** [comment]
Try to run `pkg upgrade` if you haven't done so already. Also if you could attach output of
- `pkg show termux-adb`
- `pkg show libprotobuf`
- `pkg show libprotobuf-tadb-core`

**Comment by Ncorror** [comment]
Good day, Redmi 9T in adb mode detects the device, fastboot mode device not detected. How to solve this problem. And your utelite managed to unlock the bootloader and install twrp on poco x3 pro, but redmi 9t does not give in

**Comment by Ncorror** [comment]
> Вы можете использовать `termux-usb -l`команду 
That's right, from the dexp bl250 android 8.1 device, the redmi 9t device was detected in fastboot mode. The problem is most likely in the termux-api utility, which does not work correctly on the A11-14 oss rom. And thank you very much for making my dream come true, I have been waiting for a long time for a good person to take on this matter. Thank you

**Comment by nohajc** [comment]
@Ncorror I'm happy you find it useful. :)
