### ISSUE TITLE
Unable to pop up usb authorization

### ISSUE THREAD

**Issue by Superstupid-UX** [nohajc/termux-adb#26]
I can't connect to the device after executing termux-usb -r "..." adb devices cannot obtain the device, cannot execute any adb instructions, and cannot pop up the usb authorization.

**Comment by nohajc** [comment]
What does `termux-usb -l` show when you have a device connected?

Anyway, if you're having trouble with termux-usb, it should be reported to Termux developers.

**Comment by nohajc** [comment]
Closed for inactivity.
