### ISSUE TITLE
termux-adb fails with CANNOT LINK EXECUTABLE error

### ISSUE THREAD

**Issue by jroovy** [nohajc/termux-adb#28]
**Describe the bug**
termux-adb fails to run with the error `CANNOT LINK EXECUTABLE "termux-adb": cannot locate symbol "_ZN4absl12lts_2024011612log_internal10LogMessagelsIiLi0EEERS2_RKT_" referenced by "/data/data/com.termux/files/usr/lib/libprotobuf-tadb.so"...`

**To Reproduce**
Install termux-adb, then try to run termux-adb

**Expected behavior**
Running command `termux-adb devices` (or any other command) should do something

**Screenshots**
![Screenshot_20240902-002505142_1](https://github.com/user-attachments/assets/847cdeca-492e-4947-b884-bc4e82931c4f)

**Smartphone (please complete the following information):**
 - Device: Motorola G5s Plus
 - Android version: 11

**Attach output of the following commands**
- `RUST_LOG=debug ./termux-adb` (run with debug logs enabled)
- `pkg show android-tools` (show package info)
- `adb version` (show adb version)

![Screenshot_20240902-003151901_1](https://github.com/user-attachments/assets/8422b3e9-3876-4b82-8ba0-1cf562738169)

![Screenshot_20240902-003203400_1](https://github.com/user-attachments/assets/8bcc787a-dd84-446b-91b6-c2cf71dbc92e)

![Screenshot_20240902-003449046_1](https://github.com/user-attachments/assets/f9165817-f2d5-4e8c-b8a6-68f4e31b772d)

**Attach contents of the following files (after running with debug logs enabled)**
- `/data/data/com.termux/files/usr/tmp/adb.10233.log`
- `/data/data/com.termux/files/usr/tmp/termux-adb.10233.log`

/data/data/com.termux/files/usr/tmp folder is empty

**Additional context**
termux-fastboot works without any issues

**Comment by nohajc** [comment]
Thank you for the report, I will look into it soon.

**Comment by nohajc** [comment]
Yes, most likely it means I will have to make a new build. Sorry for the inconvenience.

**Comment by offici5l** [comment]
thank you for your efforts and great work. 

(It seems that the issue is in version 1-2).

___

Q:  is version 1-4 a stable or experimental ? because it works after installing it !
( of course, I did not try all the commands )


**tks you again 🙏❤️**
![IMG_20240902_102914_162.jpg](https://github.com/user-attachments/assets/9fb231b8-778f-4f93-933e-48104f247f69)

**Comment by nohajc** [comment]
You should always use the latest from my repository but the executable is `termux-adb` not `adb`. I renamed it so there isn't any conflict with the original android tools.

**Comment by offici5l** [comment]
🙏 sorry, I just noticed that 1-4 is an older version.

**Comment by nohajc** [comment]
Current version is 0.2.2-*. Although there is a slight chance the last revision of 0.2.1 might work. I am unable to test at the moment...

**Comment by nohajc** [comment]
Hi all, I released a new version, so you should be able to upgrade the package now and see if it works for you.

Cheers.

**Comment by offici5l** [comment]
Works great and tks for your great work 🙏❤️![IMG_20240903_212036_298.jpg](https://github.com/user-attachments/assets/96f8ddfa-e6a9-4735-a5d1-ff70965a9b9f)

**Comment by Damglador** [comment]
Eyo, just updated packages and it works.
Dev is chad

**Comment by jroovy** [comment]
It works now 👍
