### ISSUE TITLE
Can't see USB device in termux-adb devices

### ISSUE THREAD

**Issue by Damglador** [nohajc/termux-adb#31]
**Describe the bug**
Device is connected, I can look up it's folders and stuff, adb is enabled, adb message is visible in the notifications on other device, device is visible in termux-usb, but `termux-adb devices` displays nothing. Am I doing something wrong?

**To Reproduce**
Steps to reproduce the behavior: connect a device to other device with a USB cable. In my case its USB-C to USB-A port and from USB-A port its USB-A to microUSB cable

**Expected behavior**
Idk, show a device, maybe that's just my skill issue

**Smartphone (thing that does adb):**
 - Device: Ulefone Armor 21
 - Android version: Android 14

**Smartphone (thing that receives adb):**
 - Device: ZTE Blade V8 Mini
 - Android version: Android 7 (a bit ancient 💀)

**The Things:**
```~ $ pkg show android-tools
Package: android-tools                          Version: 35.0.2
Maintainer: @termux                             Installed-Size: 12.8 MB
Depends: abseil-cpp, brotli, libc++, liblz4, libprotobuf, pcre2, zlib, zstd
Homepage: https://developer.android.com/        Download-Size: 2020 kB
APT-Manual-Installed: yes
APT-Sources: https://grimler.se/termux/termux-main stable/main aarch64 Packages                 Description: Android platform tools
```
```
Android Debug Bridge version 1.0.41             Version 34.0.4-android-tools
Installed as /data/data/com.termux/files/usr/bin/termux-adb
Running on Linux 5.10.205-android12-9-00027-g4d6c07fc6342-ab11525972 (aarch64)
```
![adb.10209.log.zip](https://github.com/user-attachments/files/17104916/adb.10209.log.zip)

**Additional context**
A little demonstration:
```
~ $ termux-usb -l
[                                               
  "/dev/bus/usb/002/004"
]
~ $ termux-adb devices                          List of devices attached                        
~ $
```
Photo of adb message on the other phone (it's all in Ukrainian, but it says that debugging is enabled, proof: trust be bro)
![IMG_20240924_000140_062.jpg](https://github.com/user-attachments/assets/5a6079ff-717d-4082-88bf-c49aa1681ed0)

I tried doing `termux-adb usb`, but it just says:
```
~ $ termux-adb usb
error: no devices/emulators found
```
`sudo` doesn't seem to change anything.

**Comment by Damglador** [comment]
Btw adb itself works. I can self-adb my phone without a problem using local-wireless debugging
```
~ $ termux-adb shell cmd package list users
Users:
        UserInfo{0:Damglador:4c13} running
```

Achieved this with the script:
```
#!/data/data/com.termux/files/usr/bin/sh
adb devices
su -c "setprop service.adb.tcp.port 5555"
su -c "stop adbd"
su -c "start adbd"
sleep 5
adb connect localhost:5555
```

The thing for self-debugging wasn't "active" during attempts to debug other phone.

**Comment by Damglador** [comment]
I've tested adb with the same phone and cable setup on my laptop, and it can see the phone as unauthorized and prompts to authorize the laptop on the phone

**Comment by Damglador** [comment]
ALSO. I installed aShell You from F-Droid (IzzyDroid repo I think) and it also works perfectly with the same setup

**Comment by Damglador** [comment]
After further testing, it got it, kinda. After some time since I connect the device Termux:API asks permission to device, but the device itself shows in termux-adb only after a couple of minutes. In aShell You it shows instantly. Maybe its a Termux:API issue.

**Comment by nohajc** [comment]
> ALSO. I installed aShell You from F-Droid (IzzyDroid repo I think) and it also works perfectly with the same setup

I’m not actually familiar with that app. Does it work for you as an alternative?

I’m sorry to hear about these delays…
From what you describe it seems the termux-adb part is fine. Unfortunately, there’s not much I can do about the issue.

It would be interesting to try and write a native Android app which taps into the USB APIs directly.  The whole linux userspace emulation layer in Termux can potentially add its own problems.

Anyway, it’s unlikely that I would start such a project in the near future.

**Comment by Damglador** [comment]
`aShell You`: https://github.com/DP-Hridayan/aShellYou
It's only for ADB, console output is... not good, but not bad either and switching to it every time is not convenient. Maybe waiting a minute is not that big of a deal.

**Comment by Damglador** [comment]
**So more details:**
After a device connects, or after adb start if it wasn't at the time of connection, termux-api seems to do nothing for a whole minute, precisely. After that device shows in `adb devices` and commands work without any delay. Since even other built-in termux-api commands have the same issue, termux-api issue it is.

Issue report on termux-api repo: https://github.com/termux/termux-api/issues/714
