### ISSUE TITLE
Issues in android 10/11

### ISSUE THREAD

**Issue by mcagabe19** [nohajc/termux-adb#7]
hello this not a ``libusb`` issue ig but i needed help cannot link executable in lenovo smart tab m8 (tb-8505fs) and samsung galaxy tab a 8.0 2019 (sm-t290)

my devices are rooted btw

not same issue at phone (vivo y11s, android 12, not rooted)

Screenshoots:

samsung
![IMG_20230225_120111](https://user-images.githubusercontent.com/82843871/221348760-76c1e4f0-7de7-4e85-9509-f11c4038eb7d.jpg)
lenovo
![IMG_20230225_120207](https://user-images.githubusercontent.com/82843871/221348773-13824d30-0f58-4644-b3a5-fe1531d6f036.jpg)

**Comment by nohajc** [comment]
Hi, with rooted devices you should be able to use adb from the official android-tools termux package (as root of course). Can you verify that using adb directly works for you?

**Comment by mcagabe19** [comment]
im really dumb dkwldksk thanks for helping

**Comment by mcagabe19** [comment]
oh cool
