### ISSUE TITLE
How to fix 'CANNOT LINK EXECUTABLE "termux-adb": cannot locate' 

### ISSUE THREAD

**Issue by BlueAction** [nohajc/termux-adb#8]
Hello, how can I fix this error when starting termux-adb? 
![Screenshot_20230227_020529](https://user-images.githubusercontent.com/46908543/221445843-3ff6a428-df48-4dbe-9d4f-0c5933a00de8.jpg)

Full log:
CANNOT LINK EXECUTABLE "termux-adb": cannot locate symbol "_ZN6google8protobuf8internal14ArenaStringPtr3SetERKNSt6__ndk112basic_stringIcNS3_11char_traitsIcEENS3_9allocatorIcEEEEPNS0_5ArenaE" referenced by "/data/data/com.termux/files/usr/bin/termux-adb"...

**Comment by BlueAction** [comment]
> Hello, how can I fix this error when starting termux-adb? ![Screenshot_20230227_015358](https://user-images.githubusercontent.com/46908543/221445192-ee1dadb2-c70d-41b6-877a-28bb44f366fd.jpg)
> 
> Full log: CANNOT LINK EXECUTABLE "termux-adb": cannot locate symbol "_ZN6google8protobuf8internal14ArenaStringPtr3SetERKNSt6__ndk112basic_stringIcNS3_11char_traitsIcEENS3_9allocatorIcEEEEPNS0_5ArenaE" referenced by "/data/data/com.termux/files/usr/bin/termux-adb"...

**Comment by nohajc** [comment]
What's the version of Android? Do you use Termux from Google Play Store or F-Droid?

**Comment by BlueAction** [comment]
I use android 10, termux installed from F-droid

**Comment by nohajc** [comment]
Ok, I'll see if I can replicate the issue.

Do you have the `libprotobuf` package installed btw?
Could be a broken dependency.

Also the output from `ldd $(which termux-adb)` could be helpful.

**Comment by nohajc** [comment]
So, I ran `pkg upgrade` on my Termux installation and now it gives me the same linker error.

Looks like libprotobuf was upgraded and I need to recompile termux-adb against it. I'll get to it as soon as I can.

**Comment by ProjectRedis** [comment]
Same error here, but for "termux-fasboot" command still working properly, only "termux-adb" give me an error
![Screenshot_20230228-013851_Termux](https://user-images.githubusercontent.com/119506027/221653649-a5bc4be1-6cb4-4c9e-ac8d-d26e7dc7e5c9.png)

**Comment by BlueAction** [comment]
Thanks to everyone who provided an answer to my question. Updating the main `termux-adb` repository, as well as updating packages (`pkg update)` gave a positive result. Now I can identify my device.
![Screenshot_20230228_004054](https://user-images.githubusercontent.com/46908543/221702405-62c58149-abce-478b-a7a4-f0623b681662.jpg)
But another question seems to arise from this. When displaying `termux-fastboot devices` does not display the text encoding correctly is there any way to fix this?

**Comment by nohajc** [comment]
Can you open a separate issue and provide more details?

E.g. how the output of `fastboot devices` looks like if you list this particular device from a PC or a rooted phone. That would be helpful for reference.

**Comment by BlueAction** [comment]
Yeah, sure, I'll do that.

**Comment by doncarlos999** [comment]
Sorry to revive an old issue but I think protobuf has updated again as I'm getting the following error:

```
➜  ~ pkg show protobuf
Package: protobuf
Version: 2:25.1
Maintainer: @termux
Installed-Size: 4100 kB
Depends: libprotobuf (= 2:25.1)
Homepage: https://github.com/protocolbuffers/protobuf
Download-Size: 909 kB
APT-Sources: https://grimler.se/termux/termux-main stable/main aarch64 Packages
Description: Compiler for protocol buffer definition files

➜  ~ termux-adb
CANNOT LINK EXECUTABLE "termux-adb": cannot locate symbol "_ZN6google8protobuf7Message19CopyWithSourceCheckERS1_RKS1_" referenced by "/data/data/com.termux/files/usr/bin/termux-adb"...
```

Thanks in advance if you can recompile termux-adb against the newer version. And thank you for writing a great piece of software.

**Comment by nohajc** [comment]
Thanks, I'll fix it.

**Comment by nohajc** [comment]
> Thanks in advance if you can recompile termux-adb against the newer version. And thank you for writing a great piece of software.

I just published a new build. Can you verify it works for you?

**Comment by nohajc** [comment]
Ok, I'll double check what's going on. Sorry for the trouble.

**Comment by doncarlos999** [comment]
Same for me unfortunately:

```
~ pkg show termux-adb
Package: termux-adb
Version: 0.2.1-2
Maintainer: nohajc
Installed-Size: 6689 kB
Depends: brotli, libc++, liblz4, libprotobuf, libusb, termux-api, zlib, zstd
Homepage: https://github.com/nohajc/termux-adb
Download-Size: 1665 kB
APT-Manual-Installed: yes
APT-Sources: https://nohajc.github.io termux/extras aarch64 Packages
Description: Run adb and fastboot in Termux without root permissions

➜  ~ termux-adb
CANNOT LINK EXECUTABLE "termux-adb": cannot locate symbol "_ZN6google8protobuf11MessageLite15ParseFromStringENSt6__ndk117basic_string_viewIcNS2_11char_traitsIcEEEE" referenced by "/data/data/com.termux/files/usr/bin/termux-adb"...
```

Thanks for your continued support.

**Comment by nohajc** [comment]
It should work now. If you still have trouble with the latest version (0.2.1-3), you might need to do `pkg remove termux-adb`, `apt clean` and `pkg install termux-adb`.

**Comment by doncarlos999** [comment]
Working for me too. Thanks a lot!

**Comment by nohajc** [comment]
Closing for now. I'll also think about improving the situation. Perhaps I could link protobuf statically to avoid this kind of unexpected breakage.
